appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: O+pbDrN3Da3efNnzoJ7Y48gUnEN4d1JFlfI5mhAcRm5pd18Zxq2sWL/jKv5GXiyBS/bJ6fhmr8koP6ybPAQTbbvczMck+cRxQD29pYAvsSgpb+tV+KMvJVUl2lcma4Yz0NTifD73sR3iKH6Thd6QwH7beWySepUm1WH4QH3nm2usdc3+b2KjU2W2D8CbdUs5l9CYE7GL+f2hxjegNycjIXMxZxJ/2OBtFtZj7100jjgJI9Z3/9ojeoDQYSACz/gMpompL21AHS8Cb1JSbUJ9cay9K+jUA9cGkEW5lfhjB1OwiwehTp9IHe/dvD2xFX6AbpYmaASOdwOAWWPzgV1YE2q7IWyyUSoVo3dzpv9Y8ND0oU0v/IWFHTL/0jaPfXNHoqZn/B4+R5Rw7YWC8TIWxiz1W88s0h5TgBicN2g4I6BHveYG7wWVMLGijLRTUQaBmK1Pv3Ftz7qZ++gHTkT8umHI00Y639UrR7BOADkm/30v6DtG9LChQtkOIASME0pK66fIoI7K52pWu/4/M9LyzxZErAacZew/Cmm4/WzDya2ZQpKvgRnqHgM64EDd1+x436iWUXluHBAGFQzSq6jowz4DmRKU3nAcDqiryxQUydHN+A4ySFSJaWvszlSAeyPnRHxdC08us7uwS+5kvztXAtkXsqA2IxQlcOwVblM4UFM=
conda_forge_output_validation: true
